const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("documentosApp", {
  version: "2.6.0",
  getCatalog: () => ipcRenderer.invoke("catalog:get"),
  createProject: (meta) => ipcRenderer.invoke("projects:create", meta),
  listProjects: () => ipcRenderer.invoke("projects:list"),
  getProject: (id) => ipcRenderer.invoke("projects:get", id),
  saveProject: (project) => ipcRenderer.invoke("projects:save", project),
  addFiles: (projectId, kind, markerName, multiple) => ipcRenderer.invoke("projects:add-files", projectId, kind, markerName, multiple),
  removeFile: (projectId, attachmentId) => ipcRenderer.invoke("projects:remove-file", projectId, attachmentId),
  importTemplate: (association) => ipcRenderer.invoke("templates:import", association || null),
  listTemplates: () => ipcRenderer.invoke("templates:list"),
  updateTemplate: (templateId, patch) => ipcRenderer.invoke("templates:update", templateId, patch),
  deleteTemplate: (templateId) => ipcRenderer.invoke("templates:delete", templateId),
  getExternalAiGuide: (projectId) => ipcRenderer.invoke("external-ai:guide-get", projectId),
  saveExternalAiGuide: (projectId, guideText) => ipcRenderer.invoke("external-ai:guide-save", projectId, guideText),
  buildExternalAiPrompt: (projectId, mode, guideText) => ipcRenderer.invoke("external-ai:build-prompt", projectId, mode, guideText),
  previewExternalAiResponse: (projectId, rawText, mode) => ipcRenderer.invoke("external-ai:preview", projectId, rawText, mode),
  applyExternalAiResponse: (projectId, rawText, mode, overwrite) => ipcRenderer.invoke("external-ai:apply", projectId, rawText, mode, overwrite),
  undoExternalAiImport: (projectId) => ipcRenderer.invoke("external-ai:undo", projectId),
  copyText: (text) => ipcRenderer.invoke("clipboard:write", text),
  analyze: (projectId, mode) => ipcRenderer.invoke("analysis:run", projectId, mode),
  calculate: (projectId) => ipcRenderer.invoke("calculations:run", projectId),
  generate: (projectId) => ipcRenderer.invoke("documents:generate", projectId),
  archiveUpload: (projectId) => ipcRenderer.invoke("documents:archive-upload", projectId),
  openFile: (filePath) => ipcRenderer.invoke("files:open", filePath),
  showFile: (filePath) => ipcRenderer.invoke("files:show", filePath),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  getAiProviders: () => ipcRenderer.invoke("ai:get"),
  saveAiProviders: (providers) => ipcRenderer.invoke("ai:save", providers),
  getSyncStatus: () => ipcRenderer.invoke("sync:get-status"),
  listVersions: (projectId) => ipcRenderer.invoke("versions:list", projectId),
  getVersion: (projectId, version) => ipcRenderer.invoke("versions:get", projectId, version),
  restoreVersion: (projectId, version) => ipcRenderer.invoke("versions:restore", projectId, version),
  listErrors: (options) => ipcRenderer.invoke("errors:list", options || {}),
  getErrorCount: () => ipcRenderer.invoke("errors:count"),
  resolveAllErrors: () => ipcRenderer.invoke("errors:resolve-all"),
  clearResolvedErrors: () => ipcRenderer.invoke("errors:clear-resolved"),
  reportError: (payload) => ipcRenderer.invoke("errors:report", payload || {}),
  createBackup: () => ipcRenderer.invoke("backup:create"),
  restoreBackup: () => ipcRenderer.invoke("backup:restore")
});
